// <auto-generated />
namespace verk5.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Lecture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lecture));
        
        string IMigrationMetadata.Id
        {
            get { return "201304081224463_Lecture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
